version: 1.0.0.{build}
image: Visual Studio 2017

platform:
  - x64
  - Win32

configuration:
  - Release
  - Debug

install:
  - if "%platform%"=="x64" set archi=amd64
  - if "%platform%"=="x64" set build_platform=x64

  - if "%platform%"=="Win32" set archi=x86
  - if "%platform%"=="Win32" set build_platform=Win32

  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build:
  parallel: true
  verbosity: minimal

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - msbuild WagicSyntaxPlugin.sln /p:Configuration="%configuration%" /p:Platform="%build_platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - ps: >-

      $BuildPath = "$($env:APPVEYOR_BUILD_FOLDER)\bin\$($env:CONFIGURATION)_$($env:BUILD_PLATFORM)"

      Push-AppveyorArtifact "$($BuildPath)\WagicSyntaxPlugin.dll" -FileName WagicSyntaxPlugin.dll

      if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
        if ($env:BUILD_PLATFORM -eq "x64"){
          $ZipFileName = "WagicSyntaxPlugin_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
        }
        if ($env:BUILD_PLATFORM -eq "Win32"){
          $ZipFileName = "WagicSyntaxPlugin_$($env:APPVEYOR_REPO_TAG_NAME).zip"
        }
        7z a $ZipFileName "$($BuildPath)\WagicSyntaxPlugin.dll"
      }

artifacts:
  - path: WagicSyntaxPlugin*.zip
    name: releases

deploy:
  provider: GitHub
  auth_token:
    secure: TODO ADD GITHUB KEY HERE
  artifact: releases
  draft: true
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true
    configuration: Release
